In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'name': ["amir", "iran", "mina", 2564],
    'age': [25, 12, 67, 'kk'],
    'favorit poem': ["akhvan", 1111, "ebtehag", "sepehry"]
})

df.to_csv("missing_data.csv")

In [3]:
mising_values = ["kk", 2564, 1111]
df = pd.read_csv("missing_data.csv", na_values = mising_values)
df

   Unnamed: 0  name   age favorit poem
0           0  amir  25.0       akhvan
1           1  iran  12.0          NaN
2           2  mina  67.0      ebtehag
3           3   NaN   NaN      sepehry

In [4]:
df.dropna(axis=0, how = "all")

   Unnamed: 0  name   age favorit poem
0           0  amir  25.0       akhvan
1           1  iran  12.0          NaN
2           2  mina  67.0      ebtehag
3           3   NaN   NaN      sepehry

In [5]:
df["age"].fillna(df["age"].mean())

0    25.000000
1    12.000000
2    67.000000
3    34.666667
Name: age, dtype: float64

In [6]:
df["age"].fillna(10101)

0       25.0
1       12.0
2       67.0
3    10101.0
Name: age, dtype: float64

In [7]:
df["age"].fillna(method = "ffill") # bfill

C:\Users\lenovo\AppData\Local\Temp\ipykernel_3960\920181795.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["age"].fillna(method = "ffill") # bfill

0    25.0
1    12.0
2    67.0
3    67.0
Name: age, dtype: float64

In [8]:
df["age"].interpolate(method = "linear")

0    25.0
1    12.0
2    67.0
3    67.0
Name: age, dtype: float64

In [9]:
df.dropna(thresh=3)

   Unnamed: 0  name   age favorit poem
0           0  amir  25.0       akhvan
1           1  iran  12.0          NaN
2           2  mina  67.0      ebtehag

In [17]:
df1 = (df.head(1))
df2 = pd.concat([df, df1], axis=0)
df2

   Unnamed: 0  name   age favorit poem
0           0  amir  25.0       akhvan
1           1  iran  12.0          NaN
2           2  mina  67.0      ebtehag
3           3   NaN   NaN      sepehry
0           0  amir  25.0       akhvan

In [19]:
df2.duplicated().sum()

np.int64(1)

In [20]:
df2.drop_duplicates()

   Unnamed: 0  name   age favorit poem
0           0  amir  25.0       akhvan
1           1  iran  12.0          NaN
2           2  mina  67.0      ebtehag
3           3   NaN   NaN      sepehry