In [1]:
import pandas as pd
import numpy as np

In [46]:
weight = np.random.uniform(60, 100, size=(150))
rounded_weight = np.around(weight, decimals=1)

height = np.random.uniform(1.5, 2.1, size=(150))
rounded_height = np.around(height, decimals=1)

ages = np.random.randint(18, 39, size=150)

BMI = rounded_weight / rounded_height**2
rounded_BMI = np.around(BMI, decimals=1)

BMI_data = pd.DataFrame({
    "weight": rounded_weight,
    "height": rounded_height,
    "age": ages,
    "BMI": rounded_BMI
})
BMI_data
BMI_data.to_csv("BMI_data.csv")

In [48]:
test = pd.read_csv("BMI_data.csv", index_col=0)
test

     weight  height  age   BMI
0      67.5     1.8   28  20.8
1      63.6     1.8   33  19.6
2      74.0     1.9   33  20.5
3      87.6     1.7   19  30.3
4      74.7     1.8   18  23.1
..      ...     ...  ...   ...
145    88.6     2.0   34  22.2
146    78.5     2.1   27  17.8
147    98.8     1.8   19  30.5
148    78.8     1.8   22  24.3
149    65.8     1.9   24  18.2

[150 rows x 4 columns]

In [49]:
test.assign(a = test["weight"] / test["height"])
test.assign(a = lambda x : (x["weight"] / x["height"]))

     weight  height  age   BMI          a
0      67.5     1.8   28  20.8  37.500000
1      63.6     1.8   33  19.6  35.333333
2      74.0     1.9   33  20.5  38.947368
3      87.6     1.7   19  30.3  51.529412
4      74.7     1.8   18  23.1  41.500000
..      ...     ...  ...   ...        ...
145    88.6     2.0   34  22.2  44.300000
146    78.5     2.1   27  17.8  37.380952
147    98.8     1.8   19  30.5  54.888889
148    78.8     1.8   22  24.3  43.777778
149    65.8     1.9   24  18.2  34.631579

[150 rows x 5 columns]