In [1]:
import numpy as np
import pandas as pd

In [2]:
sales_number = np.random.randint(5, 25, size=(7, 3))
sales_number

array([[13,  5, 24],
       [20, 22,  5],
       [14,  7,  9],
       [ 9,  8, 18],
       [15, 11, 21],
       [20, 17,  9],
       [ 9,  6, 20]], dtype=int32)

In [3]:
weekly_sales = pd.DataFrame(sales_number,
                            index=["saturday", "sunday", "monday", "thuesday", "wednseday", "thursday", "friday"],
                            columns=["pizza", "sandwich", "burger"])
weekly_sales

           pizza  sandwich  burger
saturday      13         5      24
sunday        20        22       5
monday        14         7       9
thuesday       9         8      18
wednseday     15        11      21
thursday      20        17       9
friday         9         6      20

In [4]:
prices = np.array([25, 15, 20])
prices.shape = (1, 3)
prices.shape

(1, 3)

In [5]:
foods_sale = pd.DataFrame(prices,
                            index=["price"],
                            columns=["pizza", "sandwich", "burger"])
foods_sale

       pizza  sandwich  burger
price     25        15      20

In [6]:
weekly_sales.T.shape

(3, 7)

In [7]:
total_sale = foods_sale.dot(weekly_sales.T)
total_sale

       saturday  sunday  monday  thuesday  wednseday  thursday  friday
price       880     930     635       705        960       935     715

In [8]:
weekly_sales["total"] = total_sale.T
weekly_sales

           pizza  sandwich  burger  total
saturday      13         5      24    880
sunday        20        22       5    930
monday        14         7       9    635
thuesday       9         8      18    705
wednseday     15        11      21    960
thursday      20        17       9    935
friday         9         6      20    715

In [13]:
d2 = np.random.random_integers(10, 18, size=(3, 5))
d2

C:\Users\lenovo\AppData\Local\Temp\ipykernel_10416\104328099.py:1: DeprecationWarning: This function is deprecated. Please call randint(10, 18 + 1) instead
  d2 = np.random.random_integers(10, 18, size=(3, 5))

array([[18, 17, 17, 16, 12],
       [18, 10, 16, 15, 15],
       [14, 17, 16, 15, 16]], dtype=int32)