In [1]:
import pandas as pd

In [2]:
cars = ["bmw", "benz", "ferrari", "206"]
colors = ["white", "blue", "red", "green"]

In [5]:
car_series = pd.Series(cars, index=[1, 3, 5, 7])
car_series

1        bmw
3       benz
5    ferrari
7        206
dtype: object

In [4]:
colors_series = pd.Series(colors)
colors_series

0    white
1     blue
2      red
3    green
dtype: object

In [6]:
car_series.loc[3]

'benz'

In [7]:
car_series.iloc[3]

'206'

In [8]:
df = pd.DataFrame({"car name": cars, "color": colors})
df

  car name  color
0      bmw  white
1     benz   blue
2  ferrari    red
3      206  green

In [11]:
df.to_csv("my-cars.csv", index=False)

In [12]:
my_car = pd.read_csv("my-cars.csv")
my_car

  car name  color
0      bmw  white
1     benz   blue
2  ferrari    red
3      206  green

In [13]:
df["car name"]

0        bmw
1       benz
2    ferrari
3        206
Name: car name, dtype: object

In [16]:
df.color

0    white
1     blue
2      red
3    green
Name: color, dtype: object

In [18]:
df.columns

Index(['car name', 'color'], dtype='object')

In [19]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [21]:
df.head(2)

  car name  color
0      bmw  white
1     benz   blue

In [22]:
car.tail(2)

NameError: name 'car' is not defined